// bitmap file 
// (c) Technion IIT, Department of Electrical Engineering 2021 
// generated bythe automatic Python tool 
// resets the game. can be activated by resetN ,by the player dying or by the playing running out of time
 
 module GameRestart (

					input	 logic  GameOverN, 
					input	 logic     resetN,
					input  logic OutOfTimeN,
					output logic   restartN
);

assign restartN = ( GameOverN & resetN & OutOfTimeN);

endmodule
 
